services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  my_dbdata:
